describe('onboarding', () => {
  beforeEach(async () => {
    await ms.visit('/')
  })

  it('should show welcome screen on first visit', async () => {
    await page.evaluate(() => localStorage.clear())
    await page.reload()
    await page.waitForSelector('#welcome_headline')
    const headline = await page.$eval('#welcome_headline', e => e.textContent)
    expect(headline).toContain('cozy synced stream')
    await page.type('#profile_username', 'default')
    await ms.screenshot('welcome')
    await page.click('#getstarted')
    await page.waitForSelector('#startsession')
  })

  it('should show home on next visit', async () => {
    await page.evaluate(() => localStorage.setItem('welcomed', 'true'))
    await page.reload()
    await page.waitForSelector('#startsession')
    await page.waitForSelector('[data-home-hero="cozy"]')
    await page.waitForSelector('#home_headline')
    await page.waitForSelector('#home_watch_flow')
    const heroText = await page.$eval('[data-home-hero="cozy"]', e => e.textContent)
    const headline = await page.$eval('#home_headline', e => e.textContent)
    const watchFlow = await page.$eval('#home_watch_flow', e => e.textContent)
    const siteExamples = await page.$eval('#home_site_examples', e => e.textContent)
    expect(heroText).toContain('Start cozy room')
    expect(heroText).toContain('Join with invite')
    expect(heroText).toContain('One cat person. One bunny person.')
    expect(headline).toContain('Happy streams')
    expect(watchFlow).toContain('Cat-side picks the vibe')
    expect(watchFlow).toContain('Rabbit-side hops in')
    expect(siteExamples).toContain('YouTube')
    await page.waitForSelector('#home_feature_private')
    await page.waitForSelector('#home_feature_sync')
    await page.waitForSelector('#home_feature_sites')
  })

  it('should show friendly join guidance', async () => {
    await ms.visit('/join')
    await page.waitForSelector('#join_headline')
    await page.waitForSelector('#join_comfort_checks')
    const headline = await page.$eval('#join_headline', e => e.textContent)
    const comfortChecks = await page.$eval('#join_comfort_checks', e => e.textContent)
    expect(headline).toContain('hop into sync')
    expect(comfortChecks).toContain('Cat-side host sends one invite')
    expect(comfortChecks).toContain('Rabbit-side guest lands here')
  })
})
