jest.setTimeout(45e3)

const SESSION_HASH = 'a'.repeat(64)

async function waitForText(text: string): Promise<void> {
  await page.waitForFunction(
    expectedText =>
      Boolean(
        document.body &&
          document.body.textContent &&
          document.body.textContent.includes(expectedText)
      ),
    text
  )
}

describe('onboarding', () => {
  beforeEach(async () => {
    await ms.visit('/')
  })

  it('should show welcome screen on first visit', async () => {
    await page.evaluate(() => localStorage.clear())
    await page.reload()
    await page.waitForSelector('#welcome_headline')
    await page.waitForSelector('#welcome_watch_map')
    const headline = await page.$eval('#welcome_headline', e => e.textContent)
    const watchMap = await page.$eval('#welcome_watch_map', e => e.textContent)
    expect(headline).toContain('cozy synced stream')
    expect(watchMap).toContain('Name tag')
    expect(watchMap).toContain('Rabbit hop')
    expect(watchMap).toContain('Cozy sync')
    await page.type('#profile_username', 'default')
    await ms.screenshot('welcome')
    await page.click('#getstarted')
    await page.waitForSelector('#startsession')
  })

  it('should show home on next visit', async () => {
    await page.evaluate(() => localStorage.setItem('welcomed', 'true'))
    await page.reload()
    await page.waitForSelector('#startsession')
    await page.waitForSelector('[data-home-hero="cozy"]')
    await page.waitForSelector('#home_headline')
    await page.waitForSelector('#home_watch_launcher')
    await page.waitForSelector('#home_starter_url')
    await page.waitForSelector('#home_start_with_url')
    await page.waitForSelector('#home_starter_chips')
    await page.waitForSelector('#home_first_action_path')
    await page.waitForSelector('#home_watch_nudge')
    await page.waitForSelector('#home_easy_path')
    await page.waitForSelector('#home_source_board')
    await page.waitForSelector('#home_vibe_dock')
    await page.waitForSelector('#home_cozy_pact')
    await page.waitForSelector('#home_pocket_planner')
    await page.waitForSelector('#home_watch_flow')
    await page.waitForSelector('#home_room_preview')
    await page.waitForSelector('#home_command_center')
    const heroText = await page.$eval('[data-home-hero="cozy"]', e => e.textContent)
    const headline = await page.$eval('#home_headline', e => e.textContent)
    const watchLauncher = await page.$eval('#home_watch_launcher', e => e.textContent)
    const firstActionPath = await page.$eval('#home_first_action_path', e => e.textContent)
    const easyPath = await page.$eval('#home_easy_path', e => e.textContent)
    const sourceBoard = await page.$eval('#home_source_board', e => e.textContent)
    const vibeDock = await page.$eval('#home_vibe_dock', e => e.textContent)
    const cozyPact = await page.$eval('#home_cozy_pact', e => e.textContent)
    const pocketPlanner = await page.$eval('#home_pocket_planner', e => e.textContent)
    const watchFlow = await page.$eval('#home_watch_flow', e => e.textContent)
    const commandCenter = await page.$eval('#home_command_center', e => e.textContent)
    const siteExamples = await page.$eval('#home_site_examples', e => e.textContent)
    expect(heroText).toContain('Start cozy room')
    expect(heroText).toContain('Join with invite')
    expect(heroText).toContain('One cat person. One bunny person.')
    expect(headline).toContain('Happy streams')
    expect(watchLauncher).toContain('Tonight starter')
    expect(watchLauncher).toContain('paste once, start cozy')
    expect(watchLauncher).toContain('Start with link')
    expect(watchLauncher).toContain('Quick chips choose the lane')
    expect(watchLauncher).toContain('source already queued')
    expect(watchLauncher).toContain('Direct MP4')
    expect(watchLauncher).toContain('Miruro')
    expect(firstActionPath).toContain('01')
    expect(firstActionPath).toContain('Queue source')
    expect(firstActionPath).toContain('02')
    expect(firstActionPath).toContain('Copy invite')
    expect(firstActionPath).toContain('03')
    expect(firstActionPath).toContain('Start together')
    expect(easyPath).toContain('Paste a site')
    expect(easyPath).toContain('Watch together')
    expect(sourceBoard).toContain('Websites first')
    expect(sourceBoard).toContain('Website lane')
    expect(sourceBoard).toContain('Local lane')
    expect(vibeDock).toContain('Two comfy seats')
    expect(vibeDock).toContain('Host-led controls')
    expect(cozyPact).toContain('Couple-mode UX')
    expect(cozyPact).toContain('Cute enough to feel personal')
    expect(pocketPlanner).toContain('Pocket watch planner')
    expect(pocketPlanner).toContain('Paste the real page')
    expect(pocketPlanner).toContain('no chaos')
    expect(watchFlow).toContain('Cat-side picks the vibe')
    expect(watchFlow).toContain('Rabbit-side hops in')
    expect(commandCenter).toContain('Ready in 3 taps')
    expect(commandCenter).toContain('Exact watch page')
    expect(commandCenter).toContain('Host presses play')
    expect(siteExamples).toContain('YouTube')
    expect(siteExamples).toContain('AnimePahe')
    expect(siteExamples).toContain('Cineby')
    expect(siteExamples).toContain('Miruro')
    await page.click('#home_starter_chips button')
    const selectedStarterPlaceholder = await page.$eval(
      '#home_starter_url',
      e => (e as HTMLInputElement).placeholder
    )
    const selectedStarterText = await page.$eval('#home_watch_launcher', e => e.textContent)
    expect(selectedStarterPlaceholder).toContain('exact YouTube')
    expect(selectedStarterText).toContain('YouTube lane selected')
    await page.waitForSelector('#home_feature_private')
    await page.waitForSelector('#home_feature_sync')
    await page.waitForSelector('#home_feature_sites')
  })

  it('should start a room from a pasted home watch link', async () => {
    await page.evaluate(() => localStorage.setItem('welcomed', 'true'))
    await page.reload()
    await page.waitForSelector('#home_starter_url')

    await page.type('#home_starter_url', 'youtube.com/watch?v=home-launch')
    await page.waitForSelector('#home_starter_preview')
    const starterPreview = await page.$eval('#home_starter_preview', e => e.textContent)
    expect(starterPreview).toContain('YouTube lane')
    expect(starterPreview).toContain('HTTPS added')
    await page.click('#home_start_with_url')

    await page.waitForSelector('[data-runtime-session-shell="true"]')
    await waitForText('Website loaded')
    await waitForText('watch')
    await waitForText('Source is ready')
  })

  it('should show friendly join guidance', async () => {
    await ms.visit('/join')
    await page.waitForSelector('#join_headline')
    await page.waitForSelector('#join_comfort_checks')
    await page.waitForSelector('#join_invite_ribbon')
    await page.waitForSelector('#join_link_breakdown')
    await page.waitForSelector('#join_ready_stack')
    await page.waitForSelector('#join_invite_hint')
    await page.type(
      '#join_invite_input',
      `https://app.gethoneystream.com/#/join/${SESSION_HASH}?secret=rabbit-secret`
    )
    await page.waitForSelector('#join_invite_preview')
    const headline = await page.$eval('#join_headline', e => e.textContent)
    const comfortChecks = await page.$eval('#join_comfort_checks', e => e.textContent)
    const inviteRibbon = await page.$eval('#join_invite_ribbon', e => e.textContent)
    const linkBreakdown = await page.$eval('#join_link_breakdown', e => e.textContent)
    const readyStack = await page.$eval('#join_ready_stack', e => e.textContent)
    const inviteHint = await page.$eval('#join_invite_hint', e => e.textContent)
    const invitePreview = await page.$eval('#join_invite_preview', e => e.textContent)
    expect(headline).toContain('hop into sync')
    expect(comfortChecks).toContain('Cat-side host sends one invite')
    expect(comfortChecks).toContain('Rabbit-side guest lands here')
    expect(inviteRibbon).toContain('Paste invite')
    expect(inviteRibbon).toContain('Hop into the room')
    expect(linkBreakdown).toContain('Room ID')
    expect(linkBreakdown).toContain('Keeps the rabbit-side seat private')
    expect(inviteHint).toContain('Full invite links are best')
    expect(readyStack).toContain('Paste the whole invite')
    expect(readyStack).toContain('Land in one seat')
    expect(readyStack).toContain('Watch the same source')
    expect(invitePreview).toContain('Invite ready')
    expect(invitePreview).toContain('Secret included')
    expect(invitePreview).toContain('rabbit-side seat')
  })
})
