jest.setTimeout(30e3)

describe('onboarding', () => {
  beforeEach(async () => {
    await ms.visit('/')
  })

  it('should show welcome screen on first visit', async () => {
    await page.evaluate(() => localStorage.clear())
    await page.reload()
    await page.waitForSelector('#welcome_headline')
    const headline = await page.$eval('#welcome_headline', e => e.textContent)
    expect(headline).toContain('cozy synced stream')
    await page.type('#profile_username', 'default')
    await ms.screenshot('welcome')
    await page.click('#getstarted')
    await page.waitForSelector('#startsession')
  })

  it('should show home on next visit', async () => {
    await page.evaluate(() => localStorage.setItem('welcomed', 'true'))
    await page.reload()
    await page.waitForSelector('#startsession')
    await page.waitForSelector('[data-home-hero="cozy"]')
    await page.waitForSelector('#home_headline')
    await page.waitForSelector('#home_easy_path')
    await page.waitForSelector('#home_source_board')
    await page.waitForSelector('#home_vibe_dock')
    await page.waitForSelector('#home_cozy_pact')
    await page.waitForSelector('#home_watch_flow')
    await page.waitForSelector('#home_room_preview')
    await page.waitForSelector('#home_command_center')
    const heroText = await page.$eval('[data-home-hero="cozy"]', e => e.textContent)
    const headline = await page.$eval('#home_headline', e => e.textContent)
    const easyPath = await page.$eval('#home_easy_path', e => e.textContent)
    const sourceBoard = await page.$eval('#home_source_board', e => e.textContent)
    const vibeDock = await page.$eval('#home_vibe_dock', e => e.textContent)
    const cozyPact = await page.$eval('#home_cozy_pact', e => e.textContent)
    const watchFlow = await page.$eval('#home_watch_flow', e => e.textContent)
    const commandCenter = await page.$eval('#home_command_center', e => e.textContent)
    const siteExamples = await page.$eval('#home_site_examples', e => e.textContent)
    expect(heroText).toContain('Start cozy room')
    expect(heroText).toContain('Join with invite')
    expect(heroText).toContain('One cat person. One bunny person.')
    expect(headline).toContain('Happy streams')
    expect(easyPath).toContain('Paste a site')
    expect(easyPath).toContain('Watch together')
    expect(sourceBoard).toContain('Websites first')
    expect(sourceBoard).toContain('Website lane')
    expect(sourceBoard).toContain('Local lane')
    expect(vibeDock).toContain('Two comfy seats')
    expect(vibeDock).toContain('Host-led controls')
    expect(cozyPact).toContain('Couple-mode UX')
    expect(cozyPact).toContain('Cute enough to feel personal')
    expect(watchFlow).toContain('Cat-side picks the vibe')
    expect(watchFlow).toContain('Rabbit-side hops in')
    expect(commandCenter).toContain('Ready in 3 taps')
    expect(commandCenter).toContain('Exact watch page')
    expect(commandCenter).toContain('Host presses play')
    expect(siteExamples).toContain('YouTube')
    expect(siteExamples).toContain('AnimePahe')
    expect(siteExamples).toContain('Cineby')
    expect(siteExamples).toContain('Miruro')
    await page.waitForSelector('#home_feature_private')
    await page.waitForSelector('#home_feature_sync')
    await page.waitForSelector('#home_feature_sites')
  })

  it('should show friendly join guidance', async () => {
    await ms.visit('/join')
    await page.waitForSelector('#join_headline')
    await page.waitForSelector('#join_comfort_checks')
    await page.waitForSelector('#join_invite_ribbon')
    await page.waitForSelector('#join_link_breakdown')
    const headline = await page.$eval('#join_headline', e => e.textContent)
    const comfortChecks = await page.$eval('#join_comfort_checks', e => e.textContent)
    const inviteRibbon = await page.$eval('#join_invite_ribbon', e => e.textContent)
    const linkBreakdown = await page.$eval('#join_link_breakdown', e => e.textContent)
    expect(headline).toContain('hop into sync')
    expect(comfortChecks).toContain('Cat-side host sends one invite')
    expect(comfortChecks).toContain('Rabbit-side guest lands here')
    expect(inviteRibbon).toContain('Paste invite')
    expect(inviteRibbon).toContain('Hop into the room')
    expect(linkBreakdown).toContain('Room ID')
    expect(linkBreakdown).toContain('Keeps the rabbit-side seat private')
  })
})
