import { classifyMediaProvider, classifyMediaUrl } from './url-classifier'

describe('protocol URL classifier', () => {
  it('classifies local files, direct media URLs, and browser website pages', () => {
    expect(classifyMediaUrl('honeystream-local://clip-1')).toBe('localFile')
    expect(classifyMediaUrl('https://cdn.example.com/video.MP4?token=abc')).toBe('url')
    expect(classifyMediaUrl('https://stream.example.com/live/playlist.m3u8')).toBe('url')
    expect(classifyMediaUrl('not-a-url')).toBe('url')
    expect(classifyMediaUrl('ftp://example.com/video.mp4')).toBe('url')

    const websitePages = [
      'https://www.youtube.com/watch?v=abc123',
      'https://youtu.be/abc123',
      'https://m.youtube.com/shorts/abc123',
      'https://www.youtube.com/shorts/abc123',
      'https://youtube.com/watch?v=abc123&list=watch-party',
      'https://www.youtube.com/embed/abc123',
      'https://www.youtube.com/live/abc123',
      'https://music.youtube.com/watch?v=abc123',
      'https://tv.youtube.com/watch/abc123',
      'https://www.youtube.com/playlist?list=abc123',
      'https://www.youtube.com/@honeystream/videos',
      'https://youtu.be/abc123?t=42',
      'https://m.youtube.com/watch?v=abc123&feature=youtu.be',
      'https://youtube.com',
      'https://animepahe.ru/play/example',
      'https://animepahe.si/anime/example',
      'https://animepahe.com/watch/example',
      'https://animepahe.com/play/example?episode=3',
      'https://www.animepahe.com/watch/example?episode=6',
      'https://www.animepahe.ru/play/example',
      'https://animepahe.si/play/example?episode=2',
      'https://www.animepahe.si/play/example?episode=4',
      'https://animepahe.com/anime/example',
      'https://animepahe.ru',
      'https://cineby.app/movie/example',
      'https://cineby.to/movie/example',
      'https://watch.cineby.app/movie/example',
      'https://cdn.cineby.app/movie/example?server=beta',
      'https://cineby.app/tv/example/season/1/episode/1',
      'https://cineby.to/tv/example/season/2/episode/3',
      'https://www.cineby.to/tv/example/season/1/episode/2',
      'https://www.cineby.ru/tv/example',
      'https://cineby.app',
      'https://www.miruro.tv/watch/example',
      'https://watch.miruro.tv/watch/example?episode=2',
      'https://anime.miruro.tv/watch/example',
      'https://beta.miruro.tv/watch/example?episode=3',
      'https://miruro.to/watch/example',
      'https://miruro.tv/watch/example?episode=1',
      'https://www.miruro.to/watch/example?dub=1',
      'https://www.miruro.tv/anime/example?watch=1',
      'https://miruro.to',
      'https://streaming.example.test/watch/honeystream-night',
      'https://shows.example.test/title/honeystream-night?episode=1',
      'https://video.example.test/room/watch-party',
      'https://vimeo.com/123456789',
      'https://www.twitch.tv/honeystreamsync',
      'https://www.netflix.com/title/80057281',
      'https://www.hulu.com/watch/honeystream-test',
      'https://www.primevideo.com/detail/honeystream-test/0ABC123',
      'https://tubitv.com/movies/honeystream-test',
      'https://www.dailymotion.com/video/xhoneystream',
      'https://watch.plex.tv/movie/honeystream-test',
      'https://www.disneyplus.com/movies/honeystream-test/abc123',
      'https://www.crunchyroll.com/watch/honeystream-test',
      'https://tv.apple.com/us/movie/honeystream-test/umc.cmc.honeystream',
      'https://www.peacocktv.com/watch/playback/honeystream-test',
      'https://www.max.com/watch/movie/honeystream-test',
      'https://www.paramountplus.com/movies/video/honeystream-test',
      'https://therokuchannel.roku.com/watch/honeystream-test',
      'https://www.kanopy.com/en/product/honeystream-test',
      'https://www.bilibili.com/video/BVhoneystream',
      'https://kick.com/honeystreamsync',
      'https://rumble.com/vhoneystream-test',
      'https://odysee.com/@honeystream:sync/honeystream-test',
      'https://www.nicovideo.jp/watch/sm12345678',
      'https://www.youtube.com/watch/demo.mp4',
      'https://animepahe.ru/play/demo.m3u8',
      'https://cineby.app/movie/demo.webm',
      'https://miruro.to/watch/demo.mp4'
    ]

    for (const url of websitePages) {
      expect(classifyMediaUrl(url)).toBe('website')
    }
  })

  it('identifies supported streaming providers without trusting unrelated hosts', () => {
    expect(classifyMediaProvider('https://www.youtube.com/watch?v=abc123')).toBe('youtube')
    expect(classifyMediaProvider('https://youtu.be/abc123')).toBe('youtube')
    expect(classifyMediaProvider('https://www.youtube-nocookie.com/embed/abc123')).toBe('youtube')
    expect(classifyMediaProvider('https://music.youtube.com/watch?v=abc123')).toBe('youtube')
    expect(classifyMediaProvider('https://tv.youtube.com/watch/abc123')).toBe('youtube')
    expect(classifyMediaProvider('https://www.youtube.com/playlist?list=abc123')).toBe('youtube')
    expect(classifyMediaProvider('https://www.youtube.com/@honeystream/videos')).toBe('youtube')
    expect(classifyMediaProvider('https://m.youtube.com/watch?v=abc123&feature=youtu.be')).toBe(
      'youtube'
    )
    expect(classifyMediaProvider('https://youtube.com')).toBe('youtube')
    expect(classifyMediaProvider('https://animepahe.si/anime/example')).toBe('animepahe')
    expect(classifyMediaProvider('https://www.animepahe.ru/play/example')).toBe('animepahe')
    expect(classifyMediaProvider('https://animepahe.com/watch/example')).toBe('animepahe')
    expect(classifyMediaProvider('https://animepahe.com/play/example?episode=3')).toBe('animepahe')
    expect(classifyMediaProvider('https://www.animepahe.com/watch/example?episode=6')).toBe(
      'animepahe'
    )
    expect(classifyMediaProvider('https://www.animepahe.si/play/example?episode=4')).toBe(
      'animepahe'
    )
    expect(classifyMediaProvider('https://animepahe.ru')).toBe('animepahe')
    expect(classifyMediaProvider('https://cdn.cineby.app/movie/example?server=beta')).toBe('cineby')
    expect(classifyMediaProvider('https://video.cineby.app/movie/example')).toBe('cineby')
    expect(classifyMediaProvider('https://watch.cineby.app/movie/example')).toBe('cineby')
    expect(classifyMediaProvider('https://cineby.to/tv/example/season/2/episode/3')).toBe('cineby')
    expect(classifyMediaProvider('https://cineby.to/movie/example')).toBe('cineby')
    expect(classifyMediaProvider('https://www.cineby.to/tv/example/season/1/episode/2')).toBe(
      'cineby'
    )
    expect(classifyMediaProvider('https://www.cineby.ru/tv/example')).toBe('cineby')
    expect(classifyMediaProvider('https://cineby.app')).toBe('cineby')
    expect(classifyMediaProvider('https://beta.miruro.tv/watch/example?episode=3')).toBe('miruro')
    expect(classifyMediaProvider('https://watch.miruro.tv/watch/example')).toBe('miruro')
    expect(classifyMediaProvider('https://anime.miruro.tv/watch/example')).toBe('miruro')
    expect(classifyMediaProvider('https://miruro.tv/watch/example')).toBe('miruro')
    expect(classifyMediaProvider('https://www.miruro.tv/anime/example?watch=1')).toBe('miruro')
    expect(classifyMediaProvider('https://miruro.to/watch/example')).toBe('miruro')
    expect(classifyMediaProvider('https://miruro.to')).toBe('miruro')
    expect(classifyMediaProvider('https://youtube.com.evil/watch?v=abc123')).toBe('unknown')
    expect(classifyMediaProvider('https://animepahe.evil/play/example')).toBe('unknown')
    expect(classifyMediaProvider('https://animepahe.example.com/play/example')).toBe('unknown')
    expect(classifyMediaProvider('https://cineby.example/movie/example')).toBe('unknown')
    expect(classifyMediaProvider('https://miruro.example/watch/example')).toBe('unknown')
    expect(classifyMediaProvider('not-a-url')).toBe('unknown')
  })
})
